# Generated by Django 2.0.2 on 2018-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.TextField()),
                ('title', models.TextField()),
                ('quote', models.TextField()),
                ('who_said_it', models.TextField()),
                ('section_header', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_awesome', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='social_medias',
            field=models.ManyToManyField(to='website.social_media'),
        ),
    ]
