# Generated by Django 2.0.2 on 2018-03-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_social_media_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
