# Generated by Django 2.2.28 on 2022-07-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_lists_game_team_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_game',
            name='state',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='lists_game',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.TextField(default=''),
        ),
    ]
