# Generated by Django 2.2.28 on 2022-07-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_lists_game_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists_game',
            name='state',
            field=models.TextField(default='configuring'),
        ),
    ]
