# Generated by Django 2.2.28 on 2022-07-25 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_auto_20220723_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_game',
            name='player_order',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lists_game',
            name='players',
            field=models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lists_game',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lists_game',
            name='state',
            field=models.TextField(default='pending'),
        ),
    ]
