# Generated by Django 2.2.28 on 2022-07-25 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220725_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists_game',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lists_game',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lists_game',
            name='player_order',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lists_game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lists_game',
            name='state',
            field=models.TextField(blank=True, default='pending'),
        ),
        migrations.AlterField(
            model_name='lists_game',
            name='teams',
            field=models.ManyToManyField(blank=True, to='website.team'),
        ),
        migrations.AlterField(
            model_name='lists_game',
            name='words',
            field=models.ManyToManyField(blank=True, to='website.word'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='used',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.TextField(blank=True, default=''),
        ),
    ]
