# Generated by Django 2.2.28 on 2022-07-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20220725_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists_game',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='lists_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.lists_game'),
        ),
    ]
