# Generated by Django 2.2.28 on 2022-08-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20220727_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_game',
            name='num_words_per_player',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
