# Generated by Django 2.2.28 on 2022-08-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_lists_game_num_words_per_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_game',
            name='seconds_per_player',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='lists_game',
            name='skips_per_player',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
