# Generated by Django 2.2.28 on 2022-08-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20220809_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lists_game',
            old_name='num_words_per_player',
            new_name='words_per_player',
        ),
    ]
