# Generated by Django 2.2.28 on 2022-08-09 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0014_lists_game_players_entering_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_game',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
