# Generated by Django 2.2.28 on 2022-08-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_lists_game_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_game',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lists_game',
            name='num_rounds',
            field=models.IntegerField(default=3),
        ),
    ]
