# Generated by Django 2.2.28 on 2022-08-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20220811_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists_game',
            name='skips_per_player',
        ),
    ]
